[build-system]
requires = ["hatchling", "matplotlib", "networkx", "numpy"]
build-backend = "hatchling.build"

[project]
name = "emergent"
version = "0.0.5"
authors = [
  { name="Oluwatoni Akintola", email="oakintol@nd.edu" },
  { name="Kekoa Wong", email="me@kekoawong.com" },
]
dependencies = [
  "networkx==3.3",
  "numpy==2.0.0",
  "matplotlib==3.9.2"
]
description = "Emergent's Python module."
readme = "README.md"
requires-python = ">=3.10.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/delphictech/emergent"
Website = "https://emergent.community/"